// applications/paint/components/ErrorBoundary.tsx
import { Component, ComponentChildren } from "preact";
import { AlertTriangle, RefreshCw } from "lucide-preact";
import { showError } from "../lib/toast-manager.ts";

interface ErrorBoundaryProps {
  children: ComponentChildren;
  fallback?: ComponentChildren;
  onError?: (error: Error, errorInfo: any) => void;
  context?: string;
}

interface ErrorBoundaryState {
  hasError: boolean;
  error: Error | null;
  errorInfo: any;
}

export class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = {
      hasError: false,
      error: null,
      errorInfo: null,
    };
  }

  static getDerivedStateFromError(error: Error): Partial<ErrorBoundaryState> {
    return {
      hasError: true,
      error,
    };
  }

  componentDidCatch(error: Error, errorInfo: any) {
    console.error('ErrorBoundary caught an error:', error, errorInfo);
    
    this.setState({
      error,
      errorInfo,
    });

    // Show toast notification
    const context = this.props.context || 'Application';
    showError(`${context} Error: ${error.message}`, {
      duration: 8000,
    });

    // Call custom error handler if provided
    if (this.props.onError) {
      try {
        this.props.onError(error, errorInfo);
      } catch (handlerError) {
        console.error('Error in custom error handler:', handlerError);
      }
    }
  }

  handleRetry = () => {
    this.setState({
      hasError: false,
      error: null,
      errorInfo: null,
    });
  };

  render() {
    if (this.state.hasError) {
      // Custom fallback UI
      if (this.props.fallback) {
        return this.props.fallback;
      }

      // Default error UI
      return (
        <div class="flex flex-col items-center justify-center p-8 bg-base-100 rounded-lg border border-error/20">
          <AlertTriangle class="w-16 h-16 text-error mb-4" />
          
          <h3 class="text-lg font-semibold text-base-content mb-2">
            Something went wrong
          </h3>
          
          <p class="text-base-content/70 text-center mb-4 max-w-md">
            {this.props.context || 'The application'} encountered an unexpected error. 
            Please try again or refresh the page.
          </p>

          {/* Error details (only in development) */}
          {Deno.env.get("DENO_ENV") === "development" && this.state.error && (
            <details class="mb-4 w-full max-w-md">
              <summary class="cursor-pointer text-sm text-base-content/60 hover:text-base-content">
                Error Details
              </summary>
              <div class="mt-2 p-3 bg-base-200 rounded text-xs font-mono text-base-content/80 overflow-auto max-h-32">
                <div class="font-semibold mb-1">Error:</div>
                <div class="mb-2">{this.state.error.message}</div>
                <div class="font-semibold mb-1">Stack:</div>
                <div class="whitespace-pre-wrap">{this.state.error.stack}</div>
              </div>
            </details>
          )}

          <div class="flex gap-2">
            <button
              onClick={this.handleRetry}
              class="btn btn-primary btn-sm"
            >
              <RefreshCw class="w-4 h-4 mr-2" />
              Try Again
            </button>
            
            <button
              onClick={() => window.location.reload()}
              class="btn btn-outline btn-sm"
            >
              Refresh Page
            </button>
          </div>
        </div>
      );
    }

    return this.props.children;
  }
}

// Canvas-specific error boundary with specialized error handling
export function CanvasErrorBoundary({ children }: { children: ComponentChildren }) {
  const handleCanvasError = (error: Error, errorInfo: any) => {
    // Log canvas-specific error details
    console.error('Canvas Error Details:', {
      error: error.message,
      stack: error.stack,
      componentStack: errorInfo.componentStack,
      timestamp: new Date().toISOString(),
    });

    // You could send this to an error reporting service here
  };

  return (
    <ErrorBoundary
      context="Canvas"
      onError={handleCanvasError}
      fallback={
        <div class="flex flex-col items-center justify-center p-8 bg-base-100 rounded-lg border border-error/20 min-h-[400px]">
          <AlertTriangle class="w-16 h-16 text-error mb-4" />
          
          <h3 class="text-lg font-semibold text-base-content mb-2">
            Canvas Error
          </h3>
          
          <p class="text-base-content/70 text-center mb-4 max-w-md">
            The drawing canvas encountered an error. This might be due to:
          </p>

          <ul class="text-sm text-base-content/60 mb-4 space-y-1">
            <li>• Browser compatibility issues</li>
            <li>• Memory limitations</li>
            <li>• Corrupted drawing data</li>
            <li>• Network connectivity problems</li>
          </ul>

          <div class="flex gap-2">
            <button
              onClick={() => window.location.reload()}
              class="btn btn-primary btn-sm"
            >
              <RefreshCw class="w-4 h-4 mr-2" />
              Restart Canvas
            </button>
            
            <a href="/gallery" class="btn btn-outline btn-sm">
              Go to Gallery
            </a>
          </div>
        </div>
      }
    >
      {children}
    </ErrorBoundary>
  );
}

// sortedstorage/src/lib/components/common/ErrorBoundary.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { AlertCircle, RefreshCw, Home } from 'lucide-svelte';
	import { goto } from '$app/navigation';
	import Button from './Button.svelte';
	
	export let error: Error | null = null;
	export let reset: (() => void) | null = null;
	export let fullPage = false;
	
	let errorId = '';
	
	onMount(() => {
		// Generate unique error ID for support reference
		errorId = `ERR-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
		
		// Log error to console for debugging
		if (error) {
			console.error('Error Boundary caught:', error);
			
			// Send error to monitoring service (if configured)
			if (typeof window !== 'undefined' && window.reportError) {
				window.reportError(error, { errorId });
			}
		}
	});
	
	function handleReset() {
		if (reset) {
			reset();
		} else {
			// Fallback: reload the page
			window.location.reload();
		}
	}
	
	function goHome() {
		goto('/');
	}
</script>

<div class={fullPage ? 'min-h-screen' : 'min-h-[400px]'} class="flex items-center justify-center p-8">
	<div class="max-w-md w-full">
		<div class="bg-base-100 rounded-2xl shadow-xl p-8 text-center">
			<!-- Error Icon -->
			<div class="inline-flex items-center justify-center w-20 h-20 bg-error/10 rounded-full mb-6">
				<AlertCircle class="w-10 h-10 text-error" />
			</div>
			
			<!-- Error Message -->
			<h2 class="text-2xl font-bold text-base-content mb-2">
				Something went wrong
			</h2>
			
			<p class="text-base-content/70 mb-6">
				{error?.message || 'An unexpected error occurred. Please try again.'}
			</p>
			
			<!-- Error ID for support -->
			{#if errorId}
				<div class="bg-base-200 rounded-lg px-4 py-2 mb-6">
					<p class="text-sm text-base-content/60">
						Error ID: <code class="text-xs font-mono select-all">{errorId}</code>
					</p>
				</div>
			{/if}
			
			<!-- Actions -->
			<div class="flex gap-3 justify-center">
				{#if !fullPage}
					<Button
						variant="outline"
						icon={Home}
						on:click={goHome}
					>
						Go Home
					</Button>
				{/if}
				
				<Button
					variant="primary"
					icon={RefreshCw}
					on:click={handleReset}
				>
					Try Again
				</Button>
			</div>
			
			<!-- Debug Info (dev mode only) -->
			{#if import.meta.env.DEV && error?.stack}
				<details class="mt-6 text-left">
					<summary class="cursor-pointer text-sm text-base-content/60 hover:text-base-content">
						Show technical details
					</summary>
					<pre class="mt-2 p-3 bg-base-200 rounded-lg text-xs overflow-x-auto whitespace-pre-wrap break-words">
{error.stack}
					</pre>
				</details>
			{/if}
		</div>
	</div>
</div>

<style>
	code {
		@apply bg-base-200 px-1 py-0.5 rounded;
	}
</style>
